# Generated by Django 2.2.5 on 2019-12-10 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('action games', 'Action games'), ('action-adventure games', 'Action-adventure games'), ('adventure games', 'Adventure games'), ('role-playing games', 'Role-playing games'), ('simulation games', 'Simulation games'), ('strategy games', 'Strategy games'), ('sports games', 'Sports games'), ('puzzle games', 'Puzzle games'), ('idle games', 'Idle games')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('CHINESE', 'CHINESE'), ('SPANISH', 'SPANISH'), ('ENGLISH', 'ENGLISH'), ('HINDI', 'HINDI'), ('ARABIC', 'ARABIC'), ('PORTUGUESE', 'PORTUGUESE'), ('BENGALI', 'BENGALI'), ('RUSSIAN', 'RUSSIAN'), ('JAPANESE', 'JAPANESE'), ('LAHNDA', 'LAHNDA'), ('JAVANESE', 'JAVANESE'), ('GERMAN', 'GERMAN'), ('KOREAN', 'KOREAN'), ('FRENCH', 'FRENCH'), ('TELUGU', 'TELUGU'), ('TURKISH', 'TURKISH'), ('TAMIL', 'TAMIL'), ('VIETNAMESE', 'VIETNAMESE'), ('URDU', 'URDU')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('release_date', models.DateField(blank=True)),
                ('demo', models.CharField(max_length=100, null=True)),
                ('company', models.ManyToManyField(to='PostAndSearch.Company')),
                ('language', models.ManyToManyField(to='PostAndSearch.Language')),
                ('platform', models.ManyToManyField(to='PostAndSearch.Platform')),
                ('series', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PostAndSearch.Series')),
                ('type', models.ManyToManyField(to='PostAndSearch.GameType')),
            ],
        ),
    ]
