# Generated by Django 2.2.5 on 2019-12-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostAndSearch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='name',
            new_name='chinese_name',
        ),
        migrations.AddField(
            model_name='game',
            name='english_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='japanese_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
