# Generated by Django 2.2.5 on 2019-12-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostAndSearch', '0002_auto_20191212_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='demo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='english_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='japanese_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
