# Generated by Django 2.2.5 on 2019-12-22 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostAndSearch', '0003_auto_20191212_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company',
            new_name='companies',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='series',
            new_name='serie',
        ),
        migrations.RenameField(
            model_name='gametype',
            old_name='game_type',
            new_name='types',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='language',
            new_name='languages',
        ),
        migrations.RenameField(
            model_name='platform',
            old_name='platform',
            new_name='platforms',
        ),
    ]
