# Generated by Django 2.2.5 on 2020-01-02 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PostAndSearch', '0004_auto_20191222_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targets', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='host', max_length=40)),
                ('description', models.CharField(max_length=60, null=True)),
                ('requirement', models.CharField(max_length=100, null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('jp', 'Japanese'), ('cn', 'Chinese')], max_length=20)),
                ('player', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=2)),
                ('room_id', models.CharField(max_length=30, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PostAndSearch.Game')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PostAndSearch.Target')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='target',
            field=models.ManyToManyField(to='PostAndSearch.Target'),
        ),
    ]
