# Generated by Django 2.2.5 on 2020-01-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostAndSearch', '0006_room_create_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='password',
            new_name='game_password',
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='host',
            field=models.CharField(blank=True, default='host', max_length=40),
        ),
        migrations.AlterField(
            model_name='room',
            name='player',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='4', max_length=2),
        ),
        migrations.AlterField(
            model_name='room',
            name='requirement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
