# Generated by Django 2.2.5 on 2020-01-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostAndSearch', '0007_auto_20200102_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='version',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
