# Generated by Django 2.2.5 on 2020-01-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostAndSearch', '0012_auto_20200105_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='game',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
