# Generated by Django 3.0.3 on 2020-02-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostAndSearch', '0018_auto_20200106_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='guest_id',
            field=models.CharField(blank=True, default='guest', max_length=40),
        ),
    ]
