# Generated by Django 3.0.3 on 2020-02-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostAndSearch', '0019_room_guest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Japanese', 'Japanese'), ('Chinese', 'Chinese')], max_length=20),
        ),
    ]
